### ISSUE TITLE
Error starting startWeblogic.sh

### ISSUE THREAD

**Issue by rpereira90** [mskutin/ansible-weblogic12c#1]
I'm testing this playbook with jdk1.8.0_172 and WebLogic 12.2.1.3.0_infrastructure

Other than editing the infra-vars is there anything I need to do to make this work ?

Running "/oracle/fmw12.2.1/config/Domains/custom_domain/startWebLogic.sh"  gives me this error:

Exception in thread "main" java.lang.NoClassDefFoundError: weblogic/diagnostics/debug/DebugLogger
        at weblogic.diagnostics.debugpatch.agent.DebugPatchAgent.<clinit>(DebugPatchAgent.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: weblogic.diagnostics.debug.DebugLogger
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
FATAL ERROR in native method: processing of -javaagent failed

I'm quite new with Ansible and Oracle in general if you can help me I would appreciate it
Using the recommended versions works fine 
Thank you

**Comment by mskutin** [comment]
Hi @ATECU, could you provide more details on your setup and changes you made? Ansible debug log would be also helpful.

**Comment by rpereira90** [comment]
@mskutin thanks for replying 
 
I'm running the playbook on a virtual machine from my local computer. I didn't use the vagrant file

The virtual machine is a vagrant box "geerlingguy/centos7"

I'm using snapshots to try things again

My local machine is centos7 with ansible version 2.3.2

I'm using the user vagrant to run the playbook


I did make some changes in the role fmw-software because I was getting some permission errors executing the weblogic installer

> ansible-weblogic12c/roles/fmw-software/tasks/main.yml

##### I changed the synchronize to a copy 

- name: Copy Weblogic installation distributive on remote
  synchronize:
src: "{{ mw_installer }}"
dest: "{{ mw_installer_folder `}}" 

- name: Copy Weblogic installation distributive on remote
  copy:
    src: "{{ mw_installer }}"
dest: "{{ mw_installer_folder }}"
 owner: "{{ oracle_user }}"
group: "{{ oracle_group }}"

##### I added  become_user
- name: execute Weblogic installer
command: "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer }} -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"

- name: execute Weblogic installer
  become_user: oracle
command: "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer }} -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"

After that I could run the playbook with no issues using the jdk-8u66 and  fmw_12.2.1.2.0_infrastructure
no issues until the end

Then I tried a different Weblogic version 12.2.1.3.0_infrastructure.
(I changed the version in infra-vars )

When I run it everything goes well until it times out at  "Wait for Admin Server to startup" if I comment out that task it times out at "Wait for Managed Server to startup"

>ansible-weblogic12c/roles/start-admin-server/tasks/main.yml

Executing startWebLogic.sh manually at /oracle/fmw12.2.1/config/Domains/custom_domain/startWebLogic.sh

gives me NoClassDefFoundError error 

I tried different jdk's 
- JDK 1.8.66 
- 8u171
- 8u172

NodeManager port is listening but I remember seeing some errors in the logs saying it stopped working

Currently I can't supply you the logs, tomorrow I will post them here

Thank you

**Comment by rpereira90** [comment]
Ansible Logs

Using:
jdk-8u66 
fmw_12.2.1.2.0_infrastructure

Original Ansible playbook Log

[ansible_original_playbook.log](https://github.com/mskutin/ansible-weblogic12c/files/2077568/ansible_original_playbook.log)

Ansible playbook with my modifications: 
[ansible_modifications.log](https://github.com/mskutin/ansible-weblogic12c/files/2077562/ansible_modifications.log)


===================
Ansible Log with the new weblogic version

fmw_12.2.1.3.0_infrastructure
jdk-8u171-linux-x64.tar.gz

[ansible_wl_new_version.log](https://github.com/mskutin/ansible-weblogic12c/files/2077563/ansible_wl_new_version.log)

===================
**Manually running /oracle/fmw12.2.1/config/Domains/custom_domain/startWebLogic.sh**

.
.
JAVA Memory arguments: -Xms1024m -Xmx1024m
.
CLASSPATH=/oracle/fmw12.2.1/jdk1.8.0_171/lib/tools.jar:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/server/lib/weblogic.jar:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/../oracle_common/modules/thirdparty/ant-contrib-1.0b3.jar:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/oracle/fmw12.2.1/product/Oracle_Home/wlserver/common/derby/lib/derbynet.jar:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/common/derby/lib/derbyclient.jar:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/common/derby/lib/derby.jar
.
PATH=/oracle/fmw12.2.1/config/Domains/custom_domain/bin:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/server/bin:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/../oracle_common/modules/thirdparty/org.apache.ant/1.9.8.0.0/apache-ant-1.9.8/bin:/oracle/fmw12.2.1/jdk1.8.0_171/jre/bin:/oracle/fmw12.2.1/jdk1.8.0_171/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/oracle/fmw12.2.1/jdk1.8.0_171/bin:/home/oracle/.local/bin:/home/oracle/bin
.
***************************************************
*  To start WebLogic Server, use a username and   *
*  password assigned to an admin-level user.  For *
*  server administration, use the WebLogic Server *
*  console at http://hostname:port/console        *
***************************************************
Starting WLS with line:
/oracle/fmw12.2.1/jdk1.8.0_171/bin/java -server   -Xms1024m -Xmx1024m -cp /oracle/fmw12.2.1/product/Oracle_Home/wlserver/server/lib/weblogic-launcher.jar -Dlaunch.use.env.classpath=true -Dweblogic.Name=AdminServer -Djava.security.policy=/oracle/fmw12.2.1/product/Oracle_Home/wlserver/server/lib/weblogic.policy  -Dweblogic.ProductionModeEnabled=true -Djava.security.egd=file:///dev/urandom  -javaagent:/oracle/fmw12.2.1/product/Oracle_Home/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/oracle/fmw12.2.1/product/Oracle_Home/wlserver/server -Dweblogic.home=/oracle/fmw12.2.1/product/Oracle_Home/wlserver/server      weblogic.Server
Exception in thread "main" java.lang.NoClassDefFoundError: weblogic/diagnostics/debug/DebugLogger
        at weblogic.diagnostics.debugpatch.agent.DebugPatchAgent.<clinit>(DebugPatchAgent.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: weblogic.diagnostics.debug.DebugLogger
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
FATAL ERROR in native method: processing of -javaagent failed
/oracle/fmw12.2.1/config/Domains/custom_domain/bin/startWebLogic.sh: line 202: 20879 Aborted                 ${JAVA_HOME}/bin/java ${JAVA_VM} ${MEM_ARGS} ${LAUNCH_ARGS} -Dweblogic.Name=${SERVER_NAME} -Djava.security.policy=${WLS_POLICY_FILE} ${JAVA_OPTIONS} ${PROXY_SETTINGS} ${SERVER_CLASS}
Stopping Derby server...
Derby server stopped.

my infra-vars

![imagem](https://user-images.githubusercontent.com/28969174/41056754-10a4e612-69bd-11e8-8115-2f5c026a2895.png)



Today I tried adding com.bea.core.logging jar files to CLASSPATH
didn't work I have no idea what to do anymore

Let me know if you need anything else
Thank You

**Comment by mskutin** [comment]
formatting 🥇
Your error clearly stands for a problem with Weblogic classpath, have you considered to try the Vagrant box?

**Comment by mskutin** [comment]
Closing this for now as it seem to be irrelevant to the playbook.
